config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'prototypes#index'
  resources :prototypes, only: [:index, :new, :show,]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
	def index
	end

	def new
	end

	def show
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.
  

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="/")
      = image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px")
    .navbar-collapse.collapse.navbar-responsive-collapse
    %ul.nav.navbar-nav.navbar-right
      -if user_signed_in?
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", href: "#", role: "button"}
            %user.name
            %span.caret
          %ul.dropdown-menu{role: "menu"}
            %li
              %a{href: "#"} Profile Edit
            %li
              %a{href: "#"} Logout
        - if user_signed_in?
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'New Proto', new_prototype_path
        - else
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'New Proto', new_prototype_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", "http-equiv" => "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/header"
    = yield
    = render "layouts/footer"

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{role: "presentation"}
          %a{href: "#"} Popular PROTO
        %li{role: "presentation"}
          %a{href: "#"} Newest PROTO
      %button{type: "button", class: "btn btn-default col-lg-1"} View Tags

.container.proto-list
  .row
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{href: "/prototypes/show"}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-user
                %a{href: "#"} by user
              .proto-posted
                Apr 26
            %ul.proto-tag-list.list-inline
              %li
                %a{href: "#", class: "btn btn-default"} iPad
              %li
                %a{href: "#", class: "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{href: "/prototypes/show"}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-user
                %a{href: "#"} by user
              .proto-posted
                Apr 26
            %ul.proto-tag-list.list-inline
              %li
                %a{href: "#", class: "btn btn-default"} iPad
              %li
                %a{href: "#", class: "btn btn-default"} wireframe

    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{href: "/prototypes/show"}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-user
                %a{href: "#"} by user
              .proto-posted
                Apr 26
            %ul.proto-tag-list.list-inline
              %li
                %a{href: "#", class: "btn btn-default"} iPad
              %li
                %a{href: "#", class: "btn btn-default"} wireframe

    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{href: "/prototypes/show"}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-user
                %a{href: "#"} by user
              .proto-posted
                Apr 26
            %ul.proto-tag-list.list-inline
              %li
                %a{href: "#", class: "btn btn-default"} iPad
              %li
                %a{href: "#", class: "btn btn-default"} wireframe

    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{href: "/prototypes/show"}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-user
                %a{href: "#"} by user
              .proto-posted
                Apr 26
            %ul.proto-tag-list.list-inline
              %li
                %a{href: "#", class: "btn btn-default"} iPad
              %li
                %a{href: "#", class: "btn btn-default"} wireframe

    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{href: "/prototypes/show"}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-user
                %a{href: "#"} by user
              .proto-posted
                Apr 26
            %ul.proto-tag-list.list-inline
              %li
                %a{href: "#", class: "btn btn-default"} iPad
              %li
                %a{href: "#", class: "btn btn-default"} wireframe

    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{href: "/prototypes/show"}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-user
                %a{href: "#"} by user
              .proto-posted
                Apr 26
            %ul.proto-tag-list.list-inline
              %li
                %a{href: "#", class: "btn btn-default"} iPad
              %li
                %a{href: "#", class: "btn btn-default"} wireframe

    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{href: "/prototypes/show"}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-user
                %a{href: "#"} by user
              .proto-posted
                Apr 26
            %ul.proto-tag-list.list-inline
              %li
                %a{href: "#", class: "btn btn-default"} iPad
              %li
                %a{href: "#", class: "btn btn-default"} wireframe

.text-center
  %ul.pagination
    %li.disabled
      %a{"aria-label" => "Previous", href: "#"}
        %span{"aria-hidden" => "true"} «
    %li.active
      %a{href: "#"}
        1
        %span.sr-only (current)
    %li
      %a{href: "#"} 2
    %li
      %a{href: "#"} 3
    %li
      %a{href: "#"} 4
    %li
      %a{href: "#"} 5
    %li
      %a{"aria-label": "Next", href: "#"}
        %span{"aria-hidden": "true"} »

app/views/prototypes/new.html.haml
%form.container.proto-new{action: ""}
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        %input.proto-new-title{type: "text", placeholder: "Title"}/
    .row
      .col-md-12
        .cover-image-upload
          %input{type: "file"}/
      .col-md-12
        %ul.proto-sub-list.list-group
          %li.list-group-item.col-md-4
            .image-upload
              %input{type: "file"}/
          %li.list-group-item.col-md-4
            .image-upload
              %input{type: "file"}/
          %li.list-group-item.col-md-4
            .image-upload-plus
              %span +
    .row.proto-description
      .col-md-12
        %input{type: "text", placeholder: "Catch Copy"}/
      .col-md-12
        %textarea{name: "", cols: "30", rows: "4", placeholder: "Concept"}
      .col-md-12
        %h4 Tag List
        .row
          .col-md-3
            %input{type: "text", placeholder: "Web Design"}/
          .col-md-3
            %input{type: "text", placeholder: "UI"}/
          .col-md-3
            %input{type: "text", placeholder: "Application"}/
    .row.text-center.proto-btn
      %button.btn.btn-lg.btn-primary.btn-block{type: "submit"} Publish

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          %a{href: "#"}
            %img.media-object{alt: "64x64", "data-holder-rendered": "true", "data-src": "holder.js/64x64", src: "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzLjQ2MDkzNzUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg==", style: "width: 64px; height: 64px;"}/
        .media-body
          %h4#top-aligned-media.media-heading
            Top aligned media
          .proto-user
            %a{href: ""} by User
            %span.degree we-b inc. Designer

    .col-md-6.text-right
      %button.btn.btn-default
        = image_tag("icon_heart.svg")
        Like
        %span.num 20
  .row
    .col-md-9
      = image_tag("sample.png", class: 'img-responsive')
    .col-md-3
      %ul.proto-sub-list.list-group
        %li.list-group-item
          = image_tag("sample.png", class: 'img-responsive')
        %li.list-group-item
          = image_tag("sample.png", class: 'img-responsive')
        %li.list-group-item
          = image_tag("sample.png", class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p Type something
    .col-md-6
      %h4 Concept
      %p Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        %li
          %a{href: "#", class: "btn btn-default"} iPad
        %li
          %a{href: "#", class: "btn btn-default"} wireframe
  .row.proto-comments
    %h4.col-md-12
      Comments
      %span.num (10)
    .col-md-8
      .media
        .media-left
          %a{href: "#"}
            %img.media-object{alt: "64x64", "data-holder-rendered": "true", "data-src": "holder.js/64x64", src: "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzLjQ2MDkzNzUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg==", style: "width: 64px; height: 64px;"}/
        .media-body
          %h4#top-aligned-media.media-heading
            Top aligned media
            %a.anchorjs-link{href: "#top-aligned-media"}
              %span.anchorjs-icon
          %p Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          %p Donec sed odio dui. Nullam quis risus eget urna mollis ornare vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
      .media
        .media-left.media-middle
          %a{href: "#"}
            %img.media-object{alt: "64x64", "data-holder-rendered": "true", "data-src": "holder.js/64x64", src: "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzLjQ2MDkzNzUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg==", style: "width: 64px; height: 64px;"}/
        .media-body
          %h4#middle-aligned-media.media-heading
            Middle aligned media
            %a.anchorjs-link{href: "#middle-aligned-media"}
              %span.anchorjs-icon
          %p Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          %p Donec sed odio dui. Nullam quis risus eget urna mollis ornare vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
      .media
        .media-left.media-bottom
          %a{href: "#"}
            %img.media-object{alt: "64x64", "data-holder-rendered": "true", "data-src": "holder.js/64x64", src: "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzLjQ2MDkzNzUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg==", style: "width: 64px; height: 64px;"}/
        .media-body
          %h4#bottom-aligned-media.media-heading
            Bottom aligned media
            %a.anchorjs-link{href: "#bottom-aligned-media"}
              %span.anchorjs-icon
          %p Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          %p Donec sed odio dui. Nullam quis risus eget urna mollis ornare vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
      %form.form-inline{role: "form"}
        %h4 Write a comment
        .row
          .form-group.col-md-10
            %textarea.form-control{placeholder: "Your comments", rows: "3"}
          .form-group.col-md-2
            %button.btn.btn-primary Comment

app/views/users/edit.html.haml
%form.container.user-new{action: ""}
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        %h2 Edit Profile
        .user-name_image.row
          .user-name.col-md-10
            %input{type: "text", placeholder: "Username", value: "TECH::MASTER"}/
          .user-image.col-md-2{:style: 'background-image: url(http://泣ける動画.com/wp-content/uploads/2015/01/t0205-01.jpg);'}
            %button.btn.btn-primary Change image
            %input{type: "file"}/
        %input.user-email{type: "email", placeholder: "E-Mail", value: "wakatsuki@we-b.co.jp"}/
        %input.user-password{type: "password", placeholder: "Password"}/
      .col-md-12
        %h4 Member of
        .user-user-member.row
          .user-name.col-md-12
            %input{type: "text", placeholder: "Member", value: "we-b inc."}/
        %h4 Profile
        .user-user-profile.row
          .user-name.col-md-12
            %textarea{name: "textarea", cols: "30", rows: "4", placeholder: "Profile"}
              I designer. I'm working with we-b inc.
              I believe the everyday Web and UI / UX.
              My hobby is collecting cassette tape.
              Thank you very much in advance.
        %h4 Works
        .user-name_image.row
          .user-name.col-md-12
            %textarea{name: "textarea", cols: "30", rows: "4", placeholder: "Works"}
              2012 Sakura Internet inc. Designer
              2012 we-b inc. Designer
              2012 Life is Tech. Mentor
              2014 Cookpad inc. Designer
    .row.text-center.user-btn
      %button.btn.btn-lg.btn-primary.btn-block{type: "submit"} Save

app/views/users/index.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        %a{:href => "#"}
          %img.media-object{:alt => "64x64", "data-holder-rendered" => "true", "data-src" => "holder.js/64x64", :src => "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzLjQ2MDkzNzUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg==", :style => "width: 64px; height: 64px;"}/
      .media-body
        %h4#top-aligned-media.media-heading
          Top aligned media
          %span.label.label-default.project-number
            29
            %i Projects
        .proto-user
          %span.degree we-b inc. Designer
        .row
          .col-md-6
            %h4 Profile
            %p Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
          .col-md-6
            %h4 Works
            %p Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
.container.proto-list
  .row
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li 
                %a{:href => "#", :class => "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li 
                %a{:href => "#", :class => "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li 
                %a{:href => "#", :class => "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li 
                %a{:href => "#", :class => "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li 
                %a{:href => "#", :class => "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li 
                %a{:href => "#", :class => "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li 
                %a{:href => "#", :class => "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li 
                %a{:href => "#", :class => "btn btn-default"} wireframe
                
.text-center
  %ul.pagination
    %li.disabled
      %a{"aria-label" => "Previous", :href => "#"}
        %span{"aria-hidden" => "true"} «
    %li.active
      %a{:href => "#"}
        1
        %span.sr-only (current)
    %li
      %a{:href => "#"} 2
    %li
      %a{:href => "#"} 3
    %li
      %a{:href => "#"} 4
    %li
      %a{:href => "#"} 5
    %li
      %a{"aria-label" => "Next", :href => "#"}
        %span{"aria-hidden" => "true"} »